name: rc
description: >-
  A Dart application runtime configuration library,
  Parse configuration file resolved environment variables and path.
version: 0.0.1
repository: https://github.com/odroe/rc

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
