name: rc
description: >-
  Dart environment variables for runtime configuration, `Platform.environment` wrapper.
version: 0.3.0
repository: https://github.com/odroe/rc

environment:
  sdk: ^3.4.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.6
