name: rc
description: >-
  Dart environment variables for runtime configuration, `Platform.environment` wrapper.
version: 0.2.1
repository: https://github.com/odroe/rc

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
