name: rc
description: >-
  RC is a configuration/collection manager that uses .(dot) to set and read collection contents.
version: 0.3.1
repository: https://github.com/odroe/rc

environment:
  sdk: ^3.4.1

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.6
