name: rc
description: A Dart application runtime configuration.
version: 0.0.0-dev.0
repository: https://github.com/odroe/rc

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
